# Generated by Django 5.2.5 on 2025-12-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_shippingaddress_shipping_country'),
        ('shop', '0029_product_has_code_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productcode'),
        ),
    ]
