# Generated by Django 5.1.7 on 2025-07-16 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_date_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog_image', models.ImageField(upload_to='')),
                ('body', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 16, 15, 29, 40, 190548)),
        ),
    ]
