# Generated by Django 5.1.7 on 2025-07-16 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_blog_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 13, 22, 53, 720601, tzinfo=datetime.timezone.utc), verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 16, 16, 52, 10, 924539)),
        ),
    ]
