# Generated by Django 5.1.7 on 2025-07-16 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_blog_pub_date_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 16, 16, 53, 7, 193780)),
        ),
    ]
