# Generated by Django 5.1.7 on 2025-07-17 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_blog_body_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 17, 13, 47, 44, 296113)),
        ),
    ]
