# Generated by Django 5.1.7 on 2025-07-21 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_blog_body_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_summary',
            field=models.TextField(max_length=103, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 21, 15, 12, 0, 777318)),
        ),
    ]
