# Generated by Django 5.1.7 on 2025-07-23 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_blog_body_summary_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_summary',
            field=models.TextField(max_length=115, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 23, 16, 49, 8, 207822)),
        ),
    ]
