# Generated by Django 5.1.7 on 2025-07-26 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_blog_body_summary_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 26, 15, 56, 8, 987211)),
        ),
    ]
