# Generated by Django 5.2.5 on 2025-08-18 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_profile_country_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 8, 18, 12, 23, 45, 38465)),
        ),
    ]
