# Generated by Django 5.2.5 on 2025-10-14 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='help_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 10, 14, 14, 1, 42, 880252)),
        ),
    ]
