# Generated by Django 5.2.5 on 2025-12-12 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_quantity_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_long',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 12, 12, 13, 13, 28, 143049)),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
