# Generated by Django 5.2.5 on 2025-12-15 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_order_date_productcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcode',
            old_name='number',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 12, 15, 13, 9, 44, 421849)),
        ),
    ]
