# Generated by Django 5.2.5 on 2025-12-15 11:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_rename_number_productcode_code_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 12, 15, 15, 19, 9, 151700)),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='codes', to='shop.product'),
        ),
    ]
