# Generated by Django 5.2.5 on 2025-12-15 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_product_has_code_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 12, 15, 15, 27, 17, 284259)),
        ),
    ]
