# Generated by Django 5.2.5 on 2025-12-15 11:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 12, 15, 15, 29, 4, 302444)),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='shop.product'),
        ),
    ]
