# Generated by Django 5.2.5 on 2025-12-16 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_order_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 12, 16, 19, 9, 35, 170735)),
        ),
    ]
