# Generated by Django 5.2.5 on 2026-09-05 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_comment_confirmed_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2026, 9, 5, 10, 6, 2, 200971)),
        ),
    ]
