# Generated by Django 5.2.5 on 2026-09-05 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_order_date_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2026, 9, 5, 11, 45, 21, 822412)),
        ),
    ]
