# Generated by Django 5.2.5 on 2026-09-05 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2026, 9, 5, 14, 3, 56, 271023)),
        ),
    ]
